### ISSUE TITLE
2.3.0 release TODO

### ISSUE THREAD

**Issue by TimTaylor** [reconhub/incidence2#119]
# definitely
- [x] #118
- [x] #117
- [ ] #116 (partially done)
- [x] Add tests for all of the new methods

# maybe
- [ ] Decide on lintr setup and run before release.
- [ ] Setup some CI for revdep checks (recheck had issues, crandalf? revdepcheck?)
- [ ] #111
- [ ] Improve testing in general.
- [ ] #115
